# Generated by Django 3.0.5 on 2020-12-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(default='full-time', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Univer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('rating', models.FloatField(default=0, max_length=10)),
                ('address', models.CharField(default='Almaty', max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('news', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('points', models.IntegerField(null=True)),
                ('form_of_study', models.ForeignKey(default='full-time', on_delete=django.db.models.deletion.CASCADE, to='maintest.Study')),
                ('specialities', models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='maintest.Speciality')),
            ],
        ),
    ]
